version: '3.7'

services:
  app-service:
    image: ${PROJECT_NAME}/${SERVICE_APP_NAME}-service:${SERVICE_VERSION_TAG}
    build:
      context: ${SERVICE_APP_NAME}-docker
      dockerfile: Dockerfile-local
    container_name: ${SERVICE_CONTAINER_NAME}-local-1
    restart: unless-stopped
    ports:
      - "${SERVICE_PORT_SERVICE}:9000"
      - "${SERVICE_PORT_DEBUG}:${SERVICE_PORT_DEBUG}"
    volumes:
      - app-data:/logs
    environment:
      - PORT=${SERVICE_PORT_SERVICE}
      - DEBUG_PORT=${SERVICE_PORT_DEBUG}
    networks:
      - dummy_network
    depends_on:
      - app-service-db
  app-service-db:
    image: postgres:${SERVICE_POSTGRES_VERSION}
    container_name: ${SERVICE_CONTAINER_NAME}-db-1
    restart: unless-stopped
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - app-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PSW}
    networks:
      - dummy_network
  pgadmin:
    image: dpage/pgadmin4:${PG_ADMIN_IMAGE_NAME}
    container_name: pgadmin-dummy-1
    restart: unless-stopped
    ports:
      - "${PG_ADMIN_PORT}:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PG_ADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PG_ADMIN_PSW}
    hostname: pgadmin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - dummy_network

volumes:
  app-db-data:
    name: ${SERVICE_APP_NAME}-db-data
  app-data:
    name: ${SERVICE_APP_NAME}-data
  pgadmin-data:
    name: ${SERVICE_APP_NAME}-pgadmin-data

networks:
  dummy_network :
    name: dummy_network
