FROM openjdk:11-jdk-slim

ENV APP_PATH=install/apps \
    CONFIG_PATH=install/config \
    APP_NAME=dummy-springboot-app-service.jar \
    SPRING_APP_LOCATION=/app
ENV SPRING_CONFIG_LOCATION=${SPRING_APP_LOCATION}/config

ADD ${APP_PATH}/${APP_NAME} ${SPRING_APP_LOCATION}/service.jar
ADD ${CONFIG_PATH}/application-local.yml ${SPRING_CONFIG_LOCATION}/application.yml
ADD ${CONFIG_PATH}/application-local.properties ${SPRING_CONFIG_LOCATION}/application.properties
ADD ${CONFIG_PATH}/logback-spring-local.xml ${SPRING_CONFIG_LOCATION}/logback-spring.xml
ADD ${CONFIG_PATH}/entrypoint-local.sh /entrypoint.sh

RUN chmod 770 /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
