DROP TABLE IF EXISTS public.constants;

CREATE TABLE IF NOT EXISTS constants (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY,
    description             VARCHAR(255),
    group_id                VARCHAR(255),
    group_id_key            VARCHAR(255),
    group_id_value          VARCHAR(255),
    PRIMARY KEY (id)
);
