server:
  port: ${server.port}

spring:
  application:
    name: dummy-springboot-app-service

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://dummy-sb-db-1:5432/dummy-sb-db"
    username: "dummy"
    password: "Dummy!01"

  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true

mybatis:
  type-aliases-package: hu.kukutyin.dummy.service.app.dao.dto
  config: classpath:mybatis-config.xml

logging:
  config: file:/app/config/logback-spring.xml
